%%ALP Basic API, Written by Nakul Bende%%

%%%%api_clear%%%%

% The clear operation sets the memory content of whole reset blocks to logic ’0’
    
% INPUTS:
    % _dll_name_ = Loaded control library
    % _hdevice_ = device handle generated by allocate function 
    % _first_block_ = first block to be cleared (0) 
    % _last_block_ = last block to be cleared (15)
    
% OUTPUT:
    % _return_clear_ = Return for success/ error reporting
    
function [return_clear] = api_clear(dll_name, hdevice, first_block, last_block)

first_block = int32(first_block);
last_block = int32(last_block);
[return_clear] = calllib(dll_name, 'AlpbDevClear', hdevice, first_block, last_block);