%%ALP Basic API, Written by Nakul Bende%%

%%%%api_free%%%%

% Frees the device, and returns the mirrors to a floating position. !!Alwyas perform this beofre shutting off the mirrors!!

%INPUTS:
    % _dll_name_ = Loaded control library
    % _hdevice_ = device handle generated by allocate function 
    
% OUTPUT:
    % _return_free_ = Return for success/ error reporting

function [return_free] = api_free(dll_name, hdevice)

[return_free] = calllib(dll_name, 'AlpbDevFree', hdevice);